FROM python:3.10-slim
    
RUN apt-get update \
    && apt-get install -y --no-install-recommends apt-utils

ENV PIP_FORMAT=legacy
ENV PIP_DISABLE_PIP_VERSION_CHECK=1

RUN apt-get install -y netcat-traditional && apt-get autoremove -y

RUN adduser --disabled-password --gecos '' myuser

WORKDIR /graph_processing/

COPY . /graph_processing

RUN pip install poetry

RUN poetry install --no-interaction

RUN chmod +x wait_for_services.sh

ENTRYPOINT ["./wait_for_services.sh"]

CMD ["./run.sh", "${WORKER_PORT}"]